name: Deploy Github Pages

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v1.5.1
        with:
          arguments: client:build
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build/distributions/